# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stat.ui'
#
# Created: Sun Sep  9 14:38:36 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(300, 500)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMaximumSize(QtCore.QSize(300, 500))
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.appVer = QtGui.QLabel(Dialog)
        self.appVer.setText(_fromUtf8(""))
        self.appVer.setObjectName(_fromUtf8("appVer"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.appVer)
        self.appRev = QtGui.QLabel(Dialog)
        self.appRev.setText(_fromUtf8(""))
        self.appRev.setObjectName(_fromUtf8("appRev"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.appRev)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_6 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_8)
        self.server_name = QtGui.QLabel(Dialog)
        self.server_name.setText(_fromUtf8(""))
        self.server_name.setObjectName(_fromUtf8("server_name"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.server_name)
        self.sn_version = QtGui.QLabel(Dialog)
        self.sn_version.setText(_fromUtf8(""))
        self.sn_version.setObjectName(_fromUtf8("sn_version"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.sn_version)
        self.dent_size = QtGui.QLabel(Dialog)
        self.dent_size.setText(_fromUtf8(""))
        self.dent_size.setObjectName(_fromUtf8("dent_size"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.dent_size)
        self.label_9 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.server_address = QtGui.QLabel(Dialog)
        self.server_address.setText(_fromUtf8(""))
        self.server_address.setObjectName(_fromUtf8("server_address"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.server_address)
        self.label_10 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_11)
        self.uploads_status = QtGui.QLabel(Dialog)
        self.uploads_status.setText(_fromUtf8(""))
        self.uploads_status.setObjectName(_fromUtf8("uploads_status"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.uploads_status)
        self.max_file_size = QtGui.QLabel(Dialog)
        self.max_file_size.setText(_fromUtf8(""))
        self.max_file_size.setObjectName(_fromUtf8("max_file_size"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.max_file_size)
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_13)
        self.server_type = QtGui.QLabel(Dialog)
        self.server_type.setText(_fromUtf8(""))
        self.server_type.setWordWrap(True)
        self.server_type.setObjectName(_fromUtf8("server_type"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.server_type)
        self.gridLayout.addLayout(self.formLayout_2, 4, 0, 1, 1)
        self.closeDialog = QtGui.QPushButton(Dialog)
        self.closeDialog.setObjectName(_fromUtf8("closeDialog"))
        self.gridLayout.addWidget(self.closeDialog, 6, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "QTDenter - Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Application", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Application version:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Application revision:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "<hr>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Server", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Server name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Status.Net version:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Dent size limit:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Server address:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Uploads:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Max file size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Server type:", None, QtGui.QApplication.UnicodeUTF8))
        self.closeDialog.setText(QtGui.QApplication.translate("Dialog", "Close", None, QtGui.QApplication.UnicodeUTF8))

